---
title: "Green parties and the silent revolution"

subtitle: "Session 02"
  
author: "Álvaro Canalejo-Molero"

date: "Spring Term 2021-2022"

institute: "University of Lucerne"

bibliography: ../00_bibliography/cweps_syllabus.bib

csl: ../00_bibliography/apa.csl

link-citations: yes

linkcolor: blue 

fontsize: 10pt

linestretch: 2

navigation: horizontal 

output:

  beamer_presentation:

    #includes:
    #  in_header: header_pagenrs.tex

    latex_engine: xelatex
    
    theme: "Pittsburgh"
      
    #fonttheme: "serif"
    
    fonttheme: "structurebold"
    
    slide_level: 2
    
    incremental: TRUE
    
    toc: TRUE
    
    number_sections: TRUE

---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

# Loading libraries
library(knitr) # For knitting document and include_graphics function
library(kableExtra) # for LaTeX tables in Rmarkdown
library(png) # For loading and grabbing the dimensions of png files

# Loading images' paths

```


# Overview of the last session

## Overview of the last session

- Main points session 01

# 'But does it melt?' The silent revolution

## 'But does it melt?' The silent revolution

- The value change hypothesis [@Inglehart1971]

# The not so silent 'new social movements'

## The not so silent 'new social movements'

- New social movements: the role non-institutional participation channels [@Kriesi1989]

# Single-issue, niche? The green challenger parties

## Single-issue, niche? The green challenger parties

- The institutionalization of new demands [@MullerRommel1998]

- Differences and similarities with established parties (socialist and communist, liberal, conservative, Christian democrats, *agrarian*)

# The impact of Green parties across Europe

## The impact of Green parties across Europe

- Where? When? How much?

# Current trends on the Green wave

## Current trends on the Green wave

- Current trends

# References

## References {.allowframebreaks}

<div id="refs"></div>